apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
        {{- range $k, $v := .Values.podLabels }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
    spec:
      containers:
        - name: {{ include "app.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 9411
          volumeMounts:
            - name: app-config
              mountPath: /config
              readOnly: true
      volumes:
        - name: app-config
          projected:
            sources:
              - configMap:
                  name: {{ include "app.fullname" . }}-config
                  items:
                    - key: values.yaml
                      path: application-service.yml