pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = credentials('DOCKER_REGISTRY')
        GITHUB_USERNAME = credentials('GITHUB_USERNAME')
        IMAGE_TAG       = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Build & Unit Tests') {
            parallel {
                stage('Accounts') {
                    steps {
                        sh """
                            mvn -pl account-service -am clean test
                           """
                    }
                }
                stage('Blocker Service') {
                    steps {
                        sh """
                            mvn -pl blocker -am clean test
                        """
                    }
                }
            }
        }

        stage('Build And Push Docker Images') {
            steps {
//                 sh """
//                 chmod +x ./build-images.sh
//                           ./build-images.sh
//                 """
                withCredentials([string(credentialsId: 'ghcr-token', variable: 'GHCR_TOKEN')]) {
                    sh '''
                        echo "$GHCR_TOKEN" | docker login ghcr.io -u Lubov1 --password-stdin
                        export DOCKER_REGISTRY=ghcr.io/lubov1
                        chmod +x build-images.sh
                        ./build-images.sh
                    '''
                }
            }
        }


//         stage('Manual Approval for PROD') {
//             steps {
//                 input message: 'Deploy to PROD environment?', ok: 'Yes, deploy'
//             }
//         }

        stage('Helm Deploy to PROD') {
            steps {
                sh """
                helm install myapp ./kubernetes
                """
            }
        }
    }
}