spring:
  main:
    web-application-type: none
  application:
    name: exchange-generator
  kafka:
    bootstrap-servers: 'kafka:9092'
    admin:
      client-id: yandex-practicum
      fail-fast: true
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 0
      retries: 0
      properties:
        enable.idempotence: false
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics

  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      enabled: true
    metrics:
      enabled: true

  tracing:
    enabled: true
    sampling:
      probability: 1.0   # 100% спанов

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
server:
  port: 8080
rest-template-enabled: false
customFilterChain:
  needed: false
logging:
  pattern:
    level: "%5p [${spring.application.name:},trace=%X{traceId:-},span=%X{spanId:-}]"


