spring:
  cloud:
    consul:
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
      client:
        provider:
          keycloak:
            token-uri: http://keycloak:8080/realms/master/protocol/openid-connect/token

accounts:
  prefix: accounts
exchange:
  prefix: exchange
gateway:
  prefix: gateway
exchange-generator:
  prefix: exchange-generator
cash:
  prefix: cash
blocker:
  prefix: blocker
transfer:
  prefix: transfer
notifications:
  prefix: notifications


management:
  endpoints:
    web:
      exposure:
        include: health,info