spring:
  config:
    import: "consul:"
  cloud:
    consul:
      config:
        enabled: true
        prefix: config         # базовый путь в KV
        defaultContext: common
        dataKey: data          # имя ключа, где лежит сам YAML/props
        format: YAML           # YAML | PROPERTIES | KEY_VALUE
        watch:
          enabled: true        # авто-обновление при изменениях
          delay: 1000
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s

accounts:
  prefix: accounts

management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    org.springframework.cloud.consul: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.http.client: DEBUG
    org.apache.hc.client5.http: DEBUG # на случай Apache HttpClient


