spring:
  security:
    oauth2:
      client:
        registration:
          exchange-generator:
            authorization-grant-type: client_credentials
            provider: keycloak
            client-id: exchange-generator
            client-secret: exchange-generator-secret
            scope: profile,email