spring:
  security:
    oauth2:
      client:
        registration:
          exchange:
            authorization-grant-type: client_credentials
            provider: keycloak
            client-id: exchange
            client-secret: exchange-secret
            scope: profile,email