spring:
  application:
    name: gateway
    gateway:
      mvc:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true
        routes:
          - id: account-service-route
            uri: lb://accounts
            predicates:
              - Path=/accounts/**
          - id: notifications-service-route
            uri: lb://notifications
            predicates:
              - Path=/notifications/**
        forwarded:
          headers:
            enabled: true
          httpclient:
            connect-timeout: 5000
            response-timeout: 5000

  security:
    oauth2:
      client:
        registration:
          gateway:
            authorization-grant-type: client_credentials
            provider: keycloak
            client-id: gateway
            client-secret: gateway-secret
            scope: profile,email
server:
  forward-headers-strategy: native