spring:
  application:
    name: gateway-api
    gateway:
      mvc:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true
        routes:
          - id: account-service-route
            uri: lb://accounts
            predicates:
              - Path=/accounts/**
          - id: notifications-service-route
            uri: lb://notifications
            predicates:
              - Path=/notifications/**
        forwarded:
          headers:
            enabled: true
          httpclient:
            connect-timeout: 5000
            response-timeout: 5000

    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: "http://localhost:8090/realms/master/protocol/openid-connect/certs"
  server:
    port: 8084
    forward-headers-strategy: native