spring:
  security:
    oauth2:
      client:
        registration:
          transfer:
            authorization-grant-type: client_credentials
            provider: keycloak
            client-id: transfer
            client-secret: transfer-secret
            scope: profile,email
blockerService:
  needed: true
notificationsService:
  needed: true