input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["logs-topic"]
    group_id => "logstash-group"
  }
}

filter {
grok {
    match => {
      "message" => "^\[svc=%{DATA:service} user=%{DATA:user}\] %{TIMESTAMP_ISO8601:log_time} %{LOGLEVEL:level}\s+%{DATA:logger}\s+- %{GREEDYDATA:log_message}"
    }
  }

  date {
    match => [ "log_time", "YYYY-MM-dd HH:mm:ss.SSS" ]
    target => "@timestamp"
  }

  mutate {
    rename => { "log_message" => "message" }
    remove_field => ["log_time", "host", "path", "@version"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "kafka-logs-%{+YYYY.MM.dd}"
  }
}